### ISSUE TITLE
How to use get() with whatever$find?

### ISSUE THREAD

**Issue by mclate** [eunjae-lee/vuex-dry#13]
Hi.
My scenario is quite simple: find item by id out of array of items, where id is a component prop and items are taken by getter. Consider next code:

```js
  import {$get, get} from "vuex-dry";

  export default {
    name: 'Component',
    data() {
      return {
        id: null,
    },
    computed: {
      trips: get('trip/items'),
      // notWorking:  get('trip/items$find', ["id", {this: "id"}]),
      selectedTrip() {
        # This notation works. 
        return $get('trip/items$find')("id", this.id)
      }
    },
...
```

I'm able to find proper trip using `selectedTrip` computed property. I wonder what would be the right way to do it using `get` instead of `$get`, as in `notWorking` commented example (that was my attempt to make it work).

Thank you.

**Comment by eunjae-lee** [comment]
Hi there,
sorry for getting back here so late.

If you're still on this, could you provide a code sandbox so that I can try it out?
You can use the following template:
https://codesandbox.io/s/vuex-dry-template-n4vuv

**Comment by mclate** [comment]
Here is code example: https://codesandbox.io/s/get-issue-0whoq
My goal is from the list of user objects to fetch one with `id === 2`. Question in the subject is how to do that using `get` method rather than `$get`. In example above you can see that `get` is returning a function, while `$get` in `selectedUser` computed property does return what i want.

**Comment by cuebit** [comment]
@mclate `$find` is a method getter – it needs to be invoked in order to return anything other than a function. `get` uses `$get` internally so your working solution is really the correct way.

```
computed: {
  user: vm => $get('trip/items$find')("id", vm.id)
}
```
